--------------------------------------------------------
--  DDL for Table ALERTTRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "ALERTTRANSACTIONS" 
   (	"ID" VARCHAR2(300 BYTE), 
	"ACCOUNTNO" VARCHAR2(30 BYTE), 
	"SOLID" VARCHAR2(20 BYTE), 
	"ACCOUNTNAME" VARCHAR2(2000 BYTE), 
	"CURRENCY" VARCHAR2(20 BYTE), 
	"SIN" NUMBER(19,4), 
	"RECID" VARCHAR2(300 BYTE), 
	"MOBILENO" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"SMSALERTFLG" VARCHAR2(20 BYTE), 
	"EMAILALERTFLG" VARCHAR2(20 BYTE), 
	"DRFLG" VARCHAR2(20 BYTE), 
	"CRFLG" VARCHAR2(20 BYTE), 
	"SHOWBAL" VARCHAR2(20 BYTE), 
	"STATUSFLG" VARCHAR2(20 BYTE), 
	"MASKACCTNO" VARCHAR2(20 BYTE), 
	"MESSAGE" VARCHAR2(2000 BYTE), 
	"TICKETID" VARCHAR2(2000 BYTE), 
	"STATUS" VARCHAR2(2000 BYTE), 
	"ETA" VARCHAR2(50 BYTE), 
	"NAT" VARCHAR2(20 BYTE), 
	"DSAI" DATE, 
	"HSAI" VARCHAR2(20 BYTE), 
	"NARRATION" VARCHAR2(2000 BYTE), 
	"TRANTYPE" VARCHAR2(20 BYTE), 
	"TRANAMT" NUMBER(19,4), 
	"BALANCE" NUMBER(19,4), 
	"POSTEDDATE" DATE, 
	"RCREDATE" DATE DEFAULT sysdate, 
	"ALERTTYPE" VARCHAR2(20 BYTE), 
	"EXTRACTTIME" DATE, 
	"DBMETHOD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DTRANSACTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DTRANSACTIONS_PK" ON "ALERTTRANSACTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALERTTRANSACTIONS_INDEX_ACCT
--------------------------------------------------------

  CREATE INDEX "ALERTTRANSACTIONS_INDEX_ACCT" ON "ALERTTRANSACTIONS" ("ACCOUNTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALERTTRANSACTIONS_RCREDATE
--------------------------------------------------------

  CREATE INDEX "ALERTTRANSACTIONS_RCREDATE" ON "ALERTTRANSACTIONS" ("RCREDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALERTTRANSACTIONS_DSAI
--------------------------------------------------------

  CREATE INDEX "ALERTTRANSACTIONS_DSAI" ON "ALERTTRANSACTIONS" ("DSAI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ALERTTRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "ALERTTRANSACTIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ALERTTRANSACTIONS" ADD CONSTRAINT "DTRANSACTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
